"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.downloadYoutubeController = void 0;
const DownloadYoutubeRepository_1 = require("../../Repository/DownloadYoutubeRepository");
const DownloadYoutubeController_1 = require("./DownloadYoutubeController");
const DownloadYoutubeUseCase_1 = require("./DownloadYoutubeUseCase");
const downloadYoutubeRepository = new DownloadYoutubeRepository_1.DownloadYoutubeRepository();
const downloadYoutubeUseCase = new DownloadYoutubeUseCase_1.DownloadYoutubeUseCase(downloadYoutubeRepository);
const downloadYoutubeController = new DownloadYoutubeController_1.DownloadYoutubeController(downloadYoutubeUseCase);
exports.downloadYoutubeController = downloadYoutubeController;
