"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.downloadTwitterController = void 0;
const DownloadTwitterRepository_1 = require("../../Repository/DownloadTwitterRepository");
const DownloadTwitterController_1 = require("./DownloadTwitterController");
const DownloadTwitterUseCase_1 = require("./DownloadTwitterUseCase");
const downloadTwitterRepository = new DownloadTwitterRepository_1.DownloadTwitterRepository();
const downloadTwitterUseCase = new DownloadTwitterUseCase_1.DownloadTwitterUseCase(downloadTwitterRepository);
const downloadTwitterController = new DownloadTwitterController_1.DownloadTwitterController(downloadTwitterUseCase);
exports.downloadTwitterController = downloadTwitterController;
